### ISSUE TITLE
Some inconsistent behavior about uncollected mounts

### ISSUE THREAD

**Issue by Grogir** [kevinclement/SimpleArmory#161]
- Most unavailable mounts are hidden if you don't own them such as the Scroll of Resurrection, Annual Pass, 10th anniversary or even the gladiator mounts, so why are the "Blizzcon" and "Collector's Edition" mop & wod mounts showing?
Those are, as far as i know, unobtainable.

- Two vicious saddle mounts are not showing if you don't own them, even though they are available ingame (lion/bear for alliance, scorpion/bear for horde).

- Also the basilisk is showing though not yet available (but it will probably be the season 3 mount so it's fine to keep it).

**Comment by seirl** [comment]
Thanks for the report!

> why are the "Blizzcon" and "Collector's Edition" mop & wod mounts showing? Those are, as far as i know, unobtainable.

The "blizzcon" mount isn't unobtainable because it's BoE, so you can ask a player to trade it to you.

The WoD collector's edition is still obtainable if you buy this: https://us.battle.net/shop/en/product/world-of-warcraft-warlords-of-draenor-digital-deluxe

The MoP collector's edition can be bought on eBay and redeemed.

> - Two vicious saddle mounts are not showing if you don't own them, even though they are available ingame (lion/bear for alliance, scorpion/bear for horde).
> - Also the basilisk is showing though not yet available (but it will probably be the season 3 mount so it's fine to keep it).

Thanks, I'll investigate that and keep you posted.

**Comment by Grogir** [comment]
Indeed i was wrong, the blizzcon mounts are not boe but you can buy a code on ebay (even for the 2017 ones)

**Comment by seirl** [comment]
Thanks, I fixed the issue of the mounts not appearing when you don't have them, and marked the Basilisk as unobtainable.
