### ISSUE TITLE
Aerie Peak Characters

### ISSUE THREAD

**Issue by SpazzWesson** [kevinclement/SimpleArmory#181]
I am unable to access any characters who are on Aerie Peak

**Comment by seirl** [comment]
Hi! Thank you for the report.

It seems that it works well both for EU and US Aerie Peak:

https://simplearmory.com/#/eu/aerie-peak/Otsenre
https://simplearmory.com/#/us/aerie-peak/Zomgitsmatt

Could you check if the problem is fixed for you as well? If it's not, please reopen this issue with a link to your character name.

Cheers.
