### ISSUE TITLE
Some achievements don't correctly show completed sub achievements

### ISSUE THREAD

**Issue by farmelle** [kevinclement/SimpleArmory#210]
Some achievements that rely on other achievements aren't correctly showing the completion status of these child achievements.  This issue appears to be across the board at the moment.

Example:
https://simplearmory.com/#/us/whisperwind/farmelle/achievements/dungeons
Vs
https://worldofwarcraft.com/en-gb/character/us/whisperwind/farmelle/achievements/dungeons-raids

![image](https://user-images.githubusercontent.com/4208884/73353598-97081c80-428b-11ea-9031-e3d33d70e9a7.png)
Compared with
![image](https://user-images.githubusercontent.com/4208884/73353626-a8e9bf80-428b-11ea-8bd0-5b631c4d2c57.png)

And another example from Quest achievements
I have Loremaster of Kul Tiras
![image](https://user-images.githubusercontent.com/4208884/73353848-3cbb8b80-428c-11ea-8182-2f84f130f59a.png)
But it's not being flagged as complete in A Nation United
![image](https://user-images.githubusercontent.com/4208884/73353946-61affe80-428c-11ea-9f1b-5d1f3db4d0bf.png)

**Comment by seirl** [comment]
Fixed in 3f5a0a70c963cd1fd11a81cd35236b799e36a621.

This was only happening with recursive criteria trees. Up until now the code was only looking at achievement criteria at a depth of exactly one in the criteria trees. I changed this so that the trees are recursively visited with a depth-first traversal. All the achievement criteria seem to be displaying properly now.
