### ISSUE TITLE
Cannot load SimpleArmory character data (or armorystats raw data)

### ISSUE THREAD

**Issue by Lorentary** [kevinclement/SimpleArmory#229]
Disclaimer: I'm not familiar with the API nor JavaScript so I don't know the specifics of what could be wrong.

When I try to load any of my characters on any of the servers I'm playing on (EU) I get the following generic error **"Could not fetch 'Kiraanta' from server 'twisting-nether'. Click here to try again."** (I've also tried Auchindoun (EU) in case there was something with the space
It is not a problem on SimpleArmory but rather it's api (or blizzards API) as trying to query the data with Excel or Python from https://armorystats.info/character/eu/twisting%20nether/kiraanta returns a 404: not found.

EDIT: This has persisted since 17th of March

**Comment by kevinclement** [comment]
Had another report of this, and tracked it down to case sensitivity problems.  You had uppercased your character name which the api doesn't like.  I've put a fix in for this so that I lowercase it all before calling the blizzard api so it should be fixed, you can use upper or lowercase.

I tried with your character and server and it looks to be working now.  Let me know if you are not seeing that.

**Comment by Lorentary** [comment]
It works now, both cases though i do not understand how it should be a case sensitivity problem that made the armorystats.info link above not respond in Excel, since there is no uppercase (It did work this morning (EU time) without any tinkering)

Welp.. The most important thing for me is that it works as i use it for my collectathon style of gameplay

Cheers!

**Comment by Lorentary** [comment]
It works now!
I can see that space has been replaced with dash and "character" has been removed from the API link
