### ISSUE TITLE
Dragon skins request

### ISSUE THREAD

**Issue by jessli9** [kevinclement/SimpleArmory#502]
Hi, first of all great work guys I love simple armory; not sure if I am in the right section and if its possible, but would be awesome if you guys can add the dragon manuscripts (skins) in the mount section. I as a mount collector feel its part of the collection :) 
Thank you

**Comment by maxdekrieger** [comment]
Hi! Since 10.0.5, achievements for the mount skins were added under the cosmetic section (SimpleArmory -> Achievements -> Collections -> all the way in the bottom). It's possible to see which ones you have completed already, and see your progress for the incomplete ones.

While I agree that it fits better under mounts, adding it to the mount section would be a huge (technical) change.

**Comment by jessli9** [comment]
ok thanks for your reply :)

**Comment by maxdekrieger** [comment]
No problem, if this fully addresses your suggestion, feel free to close the issue :)

**Comment by jessli9** [comment]
sad hehe but yeah thanks will close :)
