### ISSUE TITLE
Mark gladiator mounts as unobtainable?

### ISSUE THREAD

**Issue by seirl** [kevinclement/SimpleArmory#503]
Night from discord suggests that Gladiator mounts should always be marked as unobtainable because almost nobody ends up getting them. I have no strong opinion and would be fine with it, but am curious what others think.

**Comment by maxdekrieger** [comment]
Sorry to revive an old issue, but my personal take is that SimpleArmory provides a good overview of the mounts you miss, and gives clues to what you can do at this moment to obtain them. The difficulty of obtaining a mount is irrelevant in my opinion.

**Comment by NightNeverLucky** [comment]
Hello, my suggestion was to mark them obtainable so that the mount box does not appear unless the person owns the mount already.

> SimpleArmory provides a good overview of the mounts you miss, and gives clues to what you can do at this moment to obtain them. The difficulty of obtaining a mount is irrelevant in my opinion.

Showing an empty box every season for a mount that's going to be unobtainable by more than 99.85% of the entire World of Warcraft player base is pointless and pretty annoying for most mount collectors.

From the remaining 0.15% of players, a large portion of them obtain it through transferring a character from another account which has the mount in bags (obtained from the achievement, but not learned). This is obviously against the ToS and EULA.

**Comment by NightNeverLucky** [comment]
Hello, my suggestion was to mark them unobtainable so that the mount box does not appear unless that person owns the mount already.

> SimpleArmory provides a good overview of the mounts you miss, and gives clues to what you can do at this moment to obtain them. The difficulty of obtaining a mount is irrelevant in my opinion.

Showing an empty box every season for a mount that's going to be unobtainable by more than 99.85% of the entire World of Warcraft player base is pointless and pretty annoying for most mount collectors.

From the remaining 0.15% of players, a large portion of them obtain it through transferring a character from another account which has the mount in bags (obtained from the achievement, but not learned). This is obviously against the ToS and EULA.

**Comment by kevinclement** [comment]
I'm back and forth on this, as some of us who don't raid mythic see the mythic mount as being unattainable, but I can see an argument for pure percentages here and .15 is pretty low and could be annoying.  I'm going to mark it unobtainable for now, we'll see if we get any reports from folks who think they should see it.
