### ISSUE TITLE
Discussion: Exclusive Trading Post rewards obtainable or not?

### ISSUE THREAD

**Issue by maxdekrieger** [kevinclement/SimpleArmory#539]
Hi all,

The last few months we maintained the trading post exclusive mount rewards as `notObtainable` when the month has passed. However, this is not completely accurate and consistent for the following reasons:

- We only did so for mounts, not pets/toys
- Players might have locked certain rewards until the next month(s), so they can still obtain them

For non-exclusive rewards such as mounts that were TCG/promotional before, this is not an issue as they are always obtainable in another way.

My question is: should we tag trading-post exclusive rewards with `notObtainable` after their month has ended?

**Comment by finnlux** [comment]
I thought the intent was for the Trading post items to rotate so I think I would consider them Obtainable. There are lots of things in game that are obtainable but only once a year. The only difference is we don't _know_ for sure _when_ Trading Post stuff would be back.

**Comment by SethSchutz** [comment]
I don't think its worth the effort to mark all rewards as notObtainable as we have been told these rewards will eventually recycle through in future months.

If items are marked not obtainable, going back to flag 1 or 2 items in a future month as obtainable, and then again flagging as not obtainable at the end of said month, is just not really worth it in my opinion.

**Comment by Leomelati** [comment]
I agree with @finnlux and @SethSchutz because other mounts are only available for a limited period, such as Spirit of Eche'ro, BMAH, Timewalking, and Darkmoon Faire. It wouldn't make sense to keep changing the flags for these mounts.

Another important point that wasn't mentioned is that many people use Simple Armory to plan which mounts they want to obtain. If we were to label a mount as `notObtainable`, such as the Magenta Cloud Serpent, someone might assume they can spend their Trader's Tender because they believe they will never have the chance to buy it again.

In my opinion, we should only flag something as `notObtainable` if we are certain it will not return, such as mounts obtained from AOTC, KSM, Brawler's Guild, anniversaries, or specific promotions.

**Comment by Bukama** [comment]
Agree with @Leomelati. As TradingPost is an own category it should be also clear that they might come in the future or not and only Blizz decides that.

**Comment by maxdekrieger** [comment]
Thanks for the feedback, closing this issue as it is now changed: #543
