### ISSUE TITLE
Mount and pets 10.2

### ISSUE THREAD

**Issue by Sindroel** [kevinclement/SimpleArmory#562]
All mounts and pets from 10.2 The Emerald Dream are missing. Pls update it!

P.S The situation is similar with the Traiding Post starting in November

**Comment by ttag12** [comment]
not sure I was wondering the same. Seems these guys have no time or incentive to kepp this updated more fast

**Comment by Rauko** [comment]
greetings! do you have any update on this?

**Comment by awoodyyc** [comment]
Hello everyone. Is this expected to be updated again or is the project dead?

Is anyone that has more motivation able to host this elsewhere?

**Comment by ttag12** [comment]
I think it’s dead

[cid:ttag_logo_dachmarke_kompaktvariante_e5311fbf-7751-4ad1-9b58-cf0bcbd75994.png]
Nikolai Kühl ❘ Manager IT
Phone: +49 381 77998579

Web: www.titaniumtextiles.com<http://www.titaniumtextiles.com>

Titanium Textiles AG
Hansestraße 21, D-18182 Bentwisch (Rostock)
Vorstandsvorsitzender: Dr. Florian Ehlers | Aufsichtsratsvorsitzender: Marc Lorch
HRB 14895 | Amtsgericht Rostock

​‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑
​Disclaimer​
​​​​​This message may contain confidential information and ​is intended only for the individual(s) or entities ​named above. Any review, retransmission, ​dissemination, distribution, copying or other use of ​this information by persons or entities other than ​the intended recipient is prohibited. ​Please notify the sender immediately by e‑mail if you ​have received this e‑mail by mistake and delete this ​​e‑mail from any and all computers it may be stored on. ​​No liability is accepted for any errors or omissions ​in the contents of this message which arise as a ​result of e‑mail transmission. ​​If verification is required, please request
Am 19.12.2023 um 18:48 schrieb Andrew Wood ***@***.***>:

﻿

Hello everyone. Is this expected to be updated again or is the project dead?

Is anyone that has more motivation able to host this elsewhere?

**Comment by seirl** [comment]
Folks just because people are busy for a few month doesn't mean that the project is dead.

I left a comment here: https://github.com/kevinclement/SimpleArmory/pull/561#issuecomment-1843829662

And this PR hasn't been updated to reflect the changes that were requested, which means I would have to do it myself. Why not do it instead of saying that the project is dead? Do you think it's enjoyable to have people expect timely work from you for years and say "the project is dead" as soon as someone is a bit busy after a patch launch?

BTW, those patches would be a lot easier to do if someone was for instance working on a tool to sort/rearrange categories instead of editing the json manually. It's an open source project, you can contribute!

**Comment by EagleModdz** [comment]
@seirl Sorry it took so long! I have now implemented all the feedback! #561

**Comment by awoodyyc** [comment]
@seirl I didn't mean to cause harm and I understand being busy. 7 weeks post-patch seems like an excessive delay is all.

**Comment by kevinclement** [comment]
Sorry for delay folks.  @seirl and others have done a killer job of stewarding the app while I've been real life busy and away from wow for the last couple expansions.  I've been back to playing actively now, so hopefully that should help with keeping this thing top of mind.
