### ISSUE TITLE
Heartseeker Moth, Unknown pets, Viridian Phase Hunter icon

### ISSUE THREAD

**Issue by mmofanatic90210** [kevinclement/SimpleArmory#605]
Minor issues - 
Heartseeker Moth (companion) is listed under Unknown in Dragonflight but belongs under Love is in the Air
Viridian Phase Hunter (mount) icon is broke after Plunderstorm SA update
Swarthy Warning Sign (toy) from Plunderstorm should be added (Promotion category?) https://www.wowhead.com/item=170197/swarthy-warning-sign

Suggestion -
Remove the entire 'unknown' section from Companions under Dragonflight as no one knows when, if or where they belong (as the Heartseeker above demonstrates). Add them to respective categories as they are released.

And as usual - thank you, from my collecting OCD, to the crew who maintains SA!

**Comment by SolestialDev** [comment]
> Heartseeker Moth (companion) is listed under Unknown in Dragonflight but belongs under Love is in the Air
> Remove the entire 'unknown' section from Companions under Dragonflight as no one knows when, if or where they belong (as the Heartseeker above demonstrates). Add them to respective categories as they are released.

I'm currently working on updating the pets section, will probably be done in a week or so.

> Swarthy Warning Sign (toy) from Plunderstorm should be added (Promotion category?)

This will be fixed asap, already have the changes for toys page ready, just waiting for april trading post to go live to double check everything.

> Viridian Phase Hunter (mount) icon is broke after Plunderstorm SA update
Sadly not something we can do anything about since Blizzard messed up this icon themselves.
![image](https://github.com/kevinclement/SimpleArmory/assets/150586735/9cf2226d-5c08-4811-9155-30697db0e933)

**Comment by SolestialDev** [comment]
Ended up having some spare time, all of this (minus viridian phase hunter icon) is resolved in #606

**Comment by SolestialDev** [comment]
Fixed in #606 (and wowhead fixed the icon on their end at some point)
