### ISSUE TITLE
Rogue toy Barrel of Bandanas not listed

### ISSUE THREAD

**Issue by Isareth** [kevinclement/SimpleArmory#626]
As title says, the rogue toy Barrel of Bandanas from Warlords/Legion isn't listed anywhere that I can see. Originally the toy was made available during Warlords for Dingy Coins but then Blizzard added it to the Legion Rogue class hall vendor for Coins of Air but I don't see the toy in the Warlords or Legion section

ty!

**Comment by SolestialDev** [comment]
The toy can be found under Professions > Pickpocketing. It's listed separately because it requires you to pickpocket a lot of currency rather than straight up purchase it from a vendor. Although I did notice the other Rogue toy (Barrel of Eyepatches) is listed under Order Hall so I get the confusion.

Do you think it's better suited to be listed as Order Hall or as a Pickpocketing toy? Will move one of them so it's consistent but open to hear which spot would be preferred.

**Comment by Isareth** [comment]
Having both of them be under Legion probably makes more than Profession, imo, but having them be together somewhere would be great! I completely skimmed over Profession because I didn't think it would even be there. So Legion/Warlords or it's own Pickpocketing/Rogue section would be great too!

Thank you for your super quick responses!
